name: cryptocurrency_ranking_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  # icons
  cupertino_icons: ^1.0.2

  # service
  dio: ^5.1.2

  # localization
  easy_localization: ^3.0.1

  # value based equality
  equatable: ^2.0.5

  # flutter
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^8.1.2

  # configure env file
  flutter_dotenv: ^5.1.0

  # service locator
  get_it: ^7.6.0

  # navigation
  go_router: ^6.5.7

  # local storage caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # service
  http: ^0.13.5

  # intro
  introduction_screen: ^3.1.4

  # json code generation
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0

  # lottie
  lottie: ^2.3.2

dev_dependencies:
  # runner
  build_runner: ^2.3.3

  # icon
  flutter_launcher_icons: ^0.13.0

  # linter
  flutter_lints: ^2.0.0

  # splash screen
  flutter_native_splash:
    ^2.2.19

    # flutter test
  flutter_test:
    sdk: flutter

  # local storage caching
  hive_generator: ^2.0.0

  # linter
  very_good_analysis: ^4.0.0

# app icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

# splash screen
flutter_native_splash:
  color: "#dcd5cd"
  image: assets/logo/logo.png
  color_dark: "#1b1106"
  image_dark: assets/logo/logo_dark.png

  android_12:
    image: assets/logo/logo.png
    icon_background_color: "#dcd5cd"
    image_dark: assets/logo/logo_dark.png
    icon_background_color_dark: "#1b1106"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icon/
    - assets/translations/
    - assets/intro/
    - assets/animation/
    - .env
